name: dan&rsquo;s garden
author: Dan McCormick
markdown: redcarpet
pygments: true
baseurl: /
url: 
description: A blog about code, crops, and cognition.
github: http://www.github.com/danmcc
twitter: http://www.twitter.com/danmccorm
linkedin: http://www.linkedin.com/in/mccormickdaniel
email: dan[at]codeop.com
location: Lancaster, PA
